version: "3.8"
services:
  spring-service:
    image: tomcat:8.5-jdk8
    container_name: spring-service
    volumes:
      - tomcat-docker-logs:/app/logs
      - ./spring-service/target/spring-service-1.0.0.war:/usr/local/tomcat/webapps/spring-service.war

volumes:
  tomcat-docker-logs:
